[defaults]
lockfile = ""
max-retries = 32
max-retry-delay = "5m"
udp-timeout = "5s"
rate-limit = 1
rate-limit-burst = 120

[debug]
in = "tcp/client:127.0.0.1:12345"
out = "udp/broadcast:192.168.1.255:60005"
remove-lockfile = true
udp-timeout = "1s"
log-level = "debug"
console = true
debug = true

[host]
in = "udp/listen:0.0.0.0:60005"
out = "tcp/server:0.0.0.0:12345"

[client]
in = "tcp/client:127.0.0.1:12345"
out = "udp/broadcast:192.168.1.255:60000"
interfaces = { in = "lo0", out = "" }
udp-timeout = "1s"
log-level = "info"
label = "qwerty"

[client-lo0]
in = "tcp/client:127.0.0.1:12345"
out = "udp/broadcast:192.168.1.255:60000"
udp-timeout = "1s"
log-level = "info"
label = "qwerty"

[client-ethernet]
in = "tcp/client::en3:149.248.55.183:12345"
out = "udp/broadcast:192.168.1.255:60000"
udp-timeout = "1s"
log-level = "info"
label = "qwerty"
console = true
debug = true

[client-wifi]
in = "tcp/client::en0:149.248.55.183:12345"
out = "udp/broadcast:192.168.1.255:60000"
udp-timeout = "1s"
log-level = "info"
label = "qwerty"
console = true
debug = true

[reverse-host]
in = "udp/listen:0.0.0.0:60005"
out = "tcp/client:127.0.0.1:12345"

[reverse-client]
in = "tcp/server:0.0.0.0:12345"
out = "udp/broadcast:192.168.1.255:60000"
udp-timeout = "1s"

[tls-host]
in = "udp/listen:0.0.0.0:60005"
out = "tls/server:0.0.0.0:12345"
ca-cert = "ca.cert"
cert = "server.cert"
key = "server.key"
client-auth = "required"

[tls-client]
in = "tls/client:127.0.0.1:12345"
out = "udp/broadcast:192.168.1.255:60000"
ca-cert = "ca.cert"
cert = "client.cert"
key = "client.key"
udp-timeout = "1s"

[tailscale-server]
in = "tailscale/server:uhppoted:12345"
out = "udp/broadcast:192.168.1.255:60005"
authorisation = "authkey:tskey-auth-key-goes-here"
udp-timeout = "1s"
workdir = "../runtime/uhppoted-tunnel"
console = true
debug = true

[tailscale-client]
in = "udp/listen:0.0.0.0:60000"
out = "tailscale/client::qwerty:uhppoted:12345,nolog"
authorisation = "authkey:tskey-auth-key-goes-here"
udp-timeout = "1s"
workdir = "../runtime/uhppoted-tunnel"
console = true
debug = true

[http]
in = "http/0.0.0.0:8082"
out = "udp/broadcast:192.168.1.255:60000"
udp-timeout = "1s"
html = "./examples/html"

[https]
in = "https/0.0.0.0:8443"
out = "udp/broadcast:192.168.1.255:60000"
udp-timeout = "1s"
html = "./examples/html"

[ip]
in = "udp/listen:0.0.0.0:60000"
out = "ip/out:192.168.1.255:60005"
console=true
debug = true

    [ip.controllers]
    405419896 = "udp::192.168.1.100:60005"
    303986753 = "tcp::192.168.1.100:60005"
    405419897 = "udp::192.168.1.100:60005"
